### ISSUE TITLE
thank you again :)

### ISSUE THREAD

**Issue by alonewolfx2** [eadf/esp8266_ping#1]
It seems working fine. i tried with and without level shifter. by the way easygpio very usefull. thank you for your all work. 
finally, do you think to port other arduino libraries?

**Comment by eadf** [comment]
I'm working on the PID library right now (github.com/br3ttb/Arduino-PID-Library)
I intend IoT-enable my soldering station - just for laughs :)

Don't know if you noticed but i pushed some updates to esp8266_ping today.

**Comment by alonewolfx2** [comment]
i saw but i didnt tried yet. 0.9.5 sdk support can be awesome :) What do you think about the VirtualWire library. reciever can be usefull 
here is link. http://www.airspayce.com/mikem/arduino/VirtualWire/

**Comment by eadf** [comment]
Yes, that could be very useful. - Imagine a standalone esp running a simple RF to mqtt bridge. That could open up the IoT world for a lot of arduinos. 

But i have no experience with RF transceivers, at all.
Right now im focusing on I²C on my spare time. Have you seen my  esp8266_mcp23017 project? 
Maybe i can do something with RF later.

**Comment by alonewolfx2** [comment]
yes that could be very usefull. and yes i saw that. someone use that chip with nodemcu and zarya's i2c driver. here is link. http://www.esp8266.com/viewtopic.php?f=19&t=660

**Comment by eadf** [comment]
I did read about someone using that chip but with the SPI interface (he didn't release any code).

At least i got this this arduino-like wrapper API :)

**Comment by alonewolfx2** [comment]
i hope you will find :)
did you saw that project? ili9341 is very cheap tft screen.
https://github.com/Perfer/esp8266_ili9341
